services:
  webui-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - open-webui:/var/lib/postgresql/data
    networks:
      - chatbot-net

  config-init:
    image: alpine
    volumes:
      - ./config.json.template:/config.json.template
      - ./config.json:/config.json
    command: >
      /bin/sh -c "envsubst < /config.json.template > /config.json"
    environment:
      - BEDROCK_API_KEY=${BEDROCK_API_KEY}

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_VERSION}
    container_name: open-webui
    depends_on:
      config-init:
        condition: service_completed_successfully
      webui-db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    ports:
      - 3002:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
      - 'WEBUI_DB_HOST=webui-db'
      - 'DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@webui-db:5432/${POSTGRES_DB}'
    volumes:
      - ./config.json:/app/backend/data/config.json
    restart: unless-stopped
    networks:
      - chatbot-net

  ollama:
    build:
      context: ../common
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - chatbot-net
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODELS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ollama-data:/root/.ollama

  bedrock-gateway:
    build:
      context: ../external/bedrock-gateway/src/
      dockerfile: Dockerfile_ecs
    container_name: bedrock-gateway
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION:-us-west-1}
      - AWS_DEFAULT_REGION=${AWS_REGION:-us-west-1}
      - API_KEY=${BEDROCK_API_KEY}
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 60s
      timeout: 15s
      retries: 5
    networks:
      - chatbot-net

volumes:
  open-webui:
  ollama-data:

networks:
  chatbot-net:
