version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "weekly"
    labels:
      - "terraform"
      - "dependencies"
