---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: detect-private-key
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-diff
          - --args=-write=true
#      - id: terraform_tflint
#        args:
#          - --args=--module
#      - id: terraform_checkov
#        args:
#          - --args=--quiet
#          - --args=--framework=terraform
      - id: terraform_trivy
        files: ^aws/

#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.39.0
#    hooks:
#      - id: markdownlint
#        args:
#          - --fix
#  - repo: https://github.com/shellcheck-py/shellcheck-py
#    rev: v0.9.0.6
#    hooks:
#      - id: shellcheck
#  - repo: https://github.com/hadolint/hadolint
#    rev: v2.12.0
#    hooks:
#      - id: hadolint
#        args:
#          - --ignore
#          - DL3008
#          - --ignore
#          - DL3013
#
