---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-merge-conflict

      - id: check-added-large-files
        args:
          - --maxkb=500

      - id: mixed-line-ending
        args:
          - --fix=lf

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_validate

      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-diff
          - --args=-write=true

      - id: infracost_breakdown
        args:
          - --args=--path=./aws
          - --args=--terraform-var-file="terraform.tfvars"
        verbose: true # Always show costs

      - id: terraform_trivy
        files: ^aws/
        args:
          - --args=--tf-vars terraform.tfvars
          - --args=--skip-dirs="**/.terraform"

#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.39.0
#    hooks:
#      - id: markdownlint
#        args:
#          - --fix
