FROM docker.io/ollama/ollama:latest

# Install curl y gettext
RUN apt-get update && apt-get install -y curl gettext-base && rm -rf /var/lib/apt/lists/*

# Create and ensure the ollama main folder
RUN mkdir -p /root/.ollama && chmod 755 /root/.ollama

# Copy bootstrap script
COPY init-ollama.sh /usr/local/bin/init-ollama.sh
RUN chmod +x /usr/local/bin/init-ollama.sh

# Default Port
EXPOSE 11434

# ENV fallback var
ENV INSTALLED_MODELS=tinyllama
ENV OLLAMA_HOST=0.0.0.0

VOLUME ["/root/.ollama"]

# Use /bin/bash explicit to launch bootstrap script
ENTRYPOINT ["/bin/bash", "/usr/local/bin/init-ollama.sh"]
